### ISSUE TITLE
Add support for static OIDC discovery metadata and JWKs

### ISSUE THREAD

**Issue by wadahiro** [hashicorp/cap#55]
**Is your feature request related to a problem? Please describe.**

This library supports OIDC implicit flow (`response_type=id_token`) which doesn't need direct communication between RP and OP, but it needs direct communication for getting OIDC discovery metadata and JWKs currently.

As a specific use case, I'd like to use https://github.com/hashicorp/vault-plugin-auth-jwt to support authentication by OIDC without direct communication. Currently, CAP does not have the API, so need to implement this using a lot of reflect package as follows, which does not seem like a very good way to do it.

https://github.com/openstandia/vault-plugin-auth-jwt/commit/9eb0e93aed0385f0044e904077ac51c933fba7ae

**Describe the solution you'd like**
For OIDC implicit flow without direct communication, I'd like to add support for static OIDC discovery metadata and JWKs.
Currently, `provider.go` has a factory func. I propose adding feature which creates the provider from static json documents for OIDC discovery metadata and JWKs.

https://github.com/hashicorp/cap/blob/bb2447f2023e5160509bd6bdf25db8cc9ab8e6fd/oidc/provider.go#L60

**Comment by austingebauer** [comment]
@wadahiro - My understanding of the implicit flow via [implicit flow steps](https://openid.net/specs/openid-connect-core-1_0.html#ImplicitFlowSteps) is that the RP does need communication with the OP for the authorization request (step 2). Where does the ID token + optional access token come from if the RP (i.e., `cap/oidc`) doesn't communicate with the OP? Perhaps you can provide a step-by-step explanation or diagram of the flow you're imagining in this case?

I agree the usage of reflect in the Vault example isn't the way we'd want to do this. We may consider doing something like this if you can explain what you're trying to achieve in more detail and how that aligns with the OIDC spec.

**Comment by wadahiro** [comment]
@austingebauer

In the case of Implicit Flow, the ID token or access token is passed to the RP via the User-Agent (browser). The RP therefore does not need to access the OP.
(In the case of Authorization Code Flow, on the other hand, the authorization code is first passed to the RP via the User-Agent, which then sends the authorization code to the OP from RP to obtain the ID token and access token.)

For clarity, I have written a detailed flow using Implicit Flow in a Vault using CAP:

![image](https://user-images.githubusercontent.com/28739/201266366-b76a0430-6296-4479-a920-34e70e83ec12.png)


As the diagram above shows, using the current CAP implementation requires direct communication from the RP (Vault) to the OP. This makes no sense to use Implicit Flow.

If the CAP supports static OIDC discovery metadata and JWKs, the following flow would be possible.

![image](https://user-images.githubusercontent.com/28739/201266393-c9a9714d-7123-4f01-bd16-b7d9a5a24f9b.png)

**Comment by jimlambrt** [comment]
Is this a theoretical position of: RP shouldn't communicate with the OP or is there some sort of security requirement driving this request?

Typically the RP will occasionally needs to communicate with the OP when keys are rotated since that can happen at any random time without notice.  In general most libraries only use discovery for provider metadata regardless of which authentication flow the client is using.

**Comment by wadahiro** [comment]
@jimlambrt 

OIDC discovery is optional in the specification, and the following mentions how public keys can be set up in the RP in a different way.

`The OP advertises its public keys via its Discovery document, or may supply this information by other means. `

Therefore, there should be few libraries that only support OIDC discovery, on the contrary. For example, [go-oidc](https://github.com/coreos/go-oidc), used by CAP, also provides an API for manual configuration as follows.

https://github.com/coreos/go-oidc/blob/fb9e00951dc7a7d035e7664a5df116c3563afbd7/oidc/oidc.go#L137-L177

> Is this a theoretical position of: the RP shouldn't communicate with the OP or is there some sort of security requirement driving this request?

It is not theoretical, it is a security requirement.
In many cases, especially in the Enterprise, the OP is protected by the company's internal network and cannot communicate directly from external RPs. This is often a security requirement and will often be set out as network policy within the company. Implicit Flow is a useful way to use OIDC in these Enterprise areas.

> Normally, the RP needs to communicate with the OP during key rotation.

As you say, key rotation needs to be taken into account. However, security does not permit direct communication with the OP, so automatic updates via OIDC discovery are not possible. An additional mechanism to synchronize public keys is required, but this is outside the scope of the OIDC specification and this library. It is for the user of the library to consider.
For example, in the sequence diagram I wrote in my previous comment, the `Administrator` gets the public key from the OP and reflects it in the RP. It should be possible to automate this process as an additional mechanism.
