### ISSUE TITLE
Next cap release

### ISSUE THREAD

**Issue by yexelan** [hashicorp/cap#72]
Hello there!

We are trying to set up Nomad's login using on-premise ADFS, but we have a problem with OIDC settings.
Since v1.5, nomad has supported OIDC provider from cap repo, but only with enabled discovery which used userinfo endpoint.
We suppose that config with disabled discovery option can help us. I mean changes from PR https://github.com/hashicorp/cap/commit/2c6463e9ffcb1ef394ccac639f193a626688e0be
My question is when you are going to release them, because I see that the last tag was on April 22.
Thanks.

**Comment by jimlambrt** [comment]
you could just update the dep to the latest commit using:
`go get github.com/hashicorp/cap@1da9f67c644c2dcf3ce3a6ad30e9c635cb74d35d`  or
`go get github.com/hashicorp/cap@main`

**Comment by jimlambrt** [comment]
🤔 But if you're using nomad, I think you need to get them to update their dependency.

**Comment by jimlambrt** [comment]
I will sort out the changelog and try to make a release, but currently there's nothing blocking nomad from updating their cap dependency to include the commits you need.

**Comment by yexelan** [comment]
> I will sort out the changelog and try to make a release, but currently there's nothing blocking nomad from updating their cap dependency to include the commits you need.

Yes, but I wanted to clarify it here first, because I'm not sure that guys from Nomad will update the non-release tag

**Comment by jimlambrt** [comment]
https://github.com/hashicorp/cap/releases/tag/v0.3.0
